-- ============================================================
-- CorroSense – Demo Seed Data
-- Run AFTER schema and RLS migrations
-- NOTE: Replace UUIDs and user emails with your actual demo user IDs
-- ============================================================

-- Demo organization
INSERT INTO organizations (id, name, slug, industry, country, contact_email) VALUES
(
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'Sonatrach Integrity Division',
    'sonatrach-integrity',
    'Oil & Gas',
    'DZ',
    'integrity@sonatrach-demo.dz'
);

-- Demo project
INSERT INTO projects (id, organization_id, name, code, description, location, status) VALUES
(
    'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'GK3 Trunk Line Assessment 2024',
    'GK3-2024',
    'Full ILI campaign for the GK3 trunk line section between Hassi Messaoud and Bejaia terminal.',
    'Hassi Messaoud – Bejaia, Algeria',
    'active'
),
(
    'c3d4e5f6-a7b8-9012-cdef-123456789012',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'In Amenas Gathering Network Audit',
    'IAGN-2024',
    'Corrosion and wall loss assessment for gathering network at In Amenas facility.',
    'In Amenas, Illizi Province, Algeria',
    'active'
);

-- Demo pipelines
INSERT INTO pipelines (id, organization_id, project_id, name, code, location, total_length_m, diameter_mm, nominal_wall_thickness_mm, material, transported_fluid, nominal_pressure_bar, commissioned_at) VALUES
(
    'd4e5f6a7-b8c9-0123-defa-234567890123',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    'GK3 Main Trunk Line',
    'GK3-MTL',
    'Hassi Messaoud to Bejaia',
    680000,
    711.2,
    9.5,
    'carbon_steel',
    'crude_oil',
    72.0,
    '1985-06-15'
),
(
    'e5f6a7b8-c9d0-1234-efab-345678901234',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'c3d4e5f6-a7b8-9012-cdef-123456789012',
    'In Amenas Condensate Header',
    'IAGN-CH1',
    'In Amenas Facility Block A',
    12400,
    273.0,
    6.4,
    'carbon_steel',
    'multiphase',
    45.0,
    '1999-03-22'
);

-- Demo inspection runs
INSERT INTO inspection_runs (id, organization_id, project_id, pipeline_id, name, inspection_date, tool_type, tool_vendor, inspected_length_m, status, comment) VALUES
(
    'f6a7b8c9-d0e1-2345-fabc-456789012345',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    'd4e5f6a7-b8c9-0123-defa-234567890123',
    'GK3 MFL Run – March 2024',
    '2024-03-15',
    'MFL',
    'PII / Baker Hughes',
    680000,
    'completed',
    'Baseline ILI run covering full trunk line. High priority due to age and operating pressure.'
),
(
    'a7b8c9d0-e1f2-3456-abcd-567890123456',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'c3d4e5f6-a7b8-9012-cdef-123456789012',
    'e5f6a7b8-c9d0-1234-efab-345678901234',
    'IAGN CH1 UT Scan – Q1 2024',
    '2024-01-28',
    'UT',
    'Applus RTD',
    12400,
    'files_uploaded',
    'Ultrasonic inline inspection for condensate header. Previous run flagged localized corrosion near KP 4.2.'
);

-- Demo uploaded files metadata (storage paths must match actual uploads)
INSERT INTO uploaded_files (id, organization_id, run_id, filename, original_name, file_size_bytes, mime_type, storage_path, storage_bucket, processing_state) VALUES
(
    'b8c9d0e1-f2a3-4567-bcde-678901234567',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'f6a7b8c9-d0e1-2345-fabc-456789012345',
    'gk3_mfl_march2024.csv',
    'GK3_MFL_Run_March2024_raw.csv',
    2847392,
    'text/csv',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890/b2c3d4e5-f6a7-8901-bcde-f12345678901/f6a7b8c9-d0e1-2345-fabc-456789012345/gk3_mfl_march2024.csv',
    'raw-inspections',
    'pending'
);

-- Demo completed analysis job
INSERT INTO analysis_jobs (id, organization_id, run_id, status, progress_pct, analyzer_version, defects_found, segments_analyzed, queued_at, started_at, completed_at) VALUES
(
    'c9d0e1f2-a3b4-5678-cdef-789012345678',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'f6a7b8c9-d0e1-2345-fabc-456789012345',
    'completed',
    100,
    'mock-v1',
    47,
    68,
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '2 days' + INTERVAL '30 seconds',
    NOW() - INTERVAL '2 days' + INTERVAL '4 minutes'
);

-- Demo defects (representative sample – real data generated by analyzer)
INSERT INTO defects (organization_id, run_id, job_id, pipeline_id, distance_from_start_m, defect_type, length_mm, width_mm, depth_mm, depth_percent, corrosion_probability, severity_level, confidence_score, risk_score, signal_strength, anomaly_index, wall_thickness_mm, nominal_thickness_mm, segment_label) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 1240.5, 'corrosion', 85.3, 42.1, 3.8, 40.0, 0.87, 'high', 0.91, 78.4, 0.72, 0.68, 5.7, 9.5, 'SEG-13'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 3870.2, 'metal_loss', 120.8, 55.4, 4.9, 51.6, 0.93, 'critical', 0.88, 91.2, 0.85, 0.79, 4.6, 9.5, 'SEG-39'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 5120.8, 'corrosion', 67.2, 31.0, 2.4, 25.3, 0.61, 'medium', 0.79, 54.3, 0.58, 0.52, 7.1, 9.5, 'SEG-52'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 7445.1, 'anomaly', 33.7, 18.2, 1.2, 12.6, 0.38, 'low', 0.71, 32.1, 0.31, 0.28, 8.3, 9.5, 'SEG-75'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 9820.4, 'corrosion', 98.4, 48.7, 4.2, 44.2, 0.89, 'critical', 0.93, 86.7, 0.81, 0.75, 5.3, 9.5, 'SEG-99'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 12300.0, 'metal_loss', 145.2, 72.6, 5.5, 57.9, 0.96, 'critical', 0.95, 94.8, 0.91, 0.88, 4.0, 9.5, 'SEG-124'),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 15780.3, 'corrosion', 54.1, 27.4, 1.8, 18.9, 0.49, 'medium', 0.74, 45.6, 0.44, 0.41, 7.7, 9.5, 'SEG-158');

-- Demo segment risk scores
INSERT INTO segment_risk_scores (organization_id, run_id, job_id, pipeline_id, segment_label, segment_start_m, segment_end_m, defect_count, dominant_severity, max_depth_percent, avg_depth_percent, avg_corrosion_probability, max_corrosion_probability, aggregated_risk_score, critical_defect_count, high_defect_count) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 'SEG-13', 1200.0, 1300.0, 3, 'high', 40.0, 28.4, 0.72, 0.87, 62.4, 0, 2),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 'SEG-39', 3800.0, 3900.0, 5, 'critical', 51.6, 38.2, 0.81, 0.93, 84.7, 2, 1),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 'SEG-52', 5100.0, 5200.0, 2, 'medium', 25.3, 18.7, 0.55, 0.61, 41.2, 0, 0),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 'SEG-99', 9800.0, 9900.0, 4, 'critical', 44.2, 35.8, 0.78, 0.89, 79.3, 1, 2),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f6a7b8c9-d0e1-2345-fabc-456789012345', 'c9d0e1f2-a3b4-5678-cdef-789012345678', 'd4e5f6a7-b8c9-0123-defa-234567890123', 'SEG-124', 12300.0, 12400.0, 6, 'critical', 57.9, 48.1, 0.89, 0.96, 92.1, 3, 2);
